### PR TITLE
Fix copy & expand button padding.

### LINKED ISSUE #326: Code Reference: After clicking code "copy", button goes big.
The button size should not change once I copy.

## Screenshot

Screenshot 2023-11-03 at 2 38 20 PM

## Steps to reproduce

1. Visit: https://developer.wordpress.org/redesign-test/reference/classes/wp_hook/
2. Click either button
3. Notice that it gets really large after clicking.

### PR DESCRIPTION
**Pull request by StevenDufresne**
Fixes #326. 

This uses classes introduced in https://github.com/WordPress/wporg-parent-2021/pull/112 to fix the buttons growing too much on `:focus`.

**Default**
Screenshot 2023-11-06 at 2 20 58 PM

**Focal States**
After the user clicks, the button text updates.
| First | Second |
|--------|--------|
| Screenshot 2023-11-06 at 2 17 15 PM | Screenshot 2023-11-06 at 2 17 18 PM |
|  Screenshot 2023-11-06 at 2 17 06 PM | Screenshot 2023-11-06 at 2 17 10 PM |

### CODE REVIEW

File: source/wp-content/themes/wporg-developer-2023/js/function-reference.js [hunk 1]
```diff
@@ -34,8 +34,8 @@ jQuery( function ( $ ) {
 
 		$element.wrap( '<div class="wporg-developer-code-block"></div>' );
 
-		const $copyButtonContainer = $( '<div class="wp-block-button is-style-outline"></div>' );
-		const $copyButton = $( '<a href="#" class="wp-block-button__link wp-element-button"></a>' );
+		const $copyButtonContainer = $( '<div class="wp-block-button is-style-outline is-small"></div>' );
+		const $copyButton = $( '<a href="#" class="wp-block-button__link wp-element-button has-background"></a>' );
```
Comment (adamwoodnz) [inline source/wp-content/themes/wporg-developer-2023/js/function-reference.js:38]: Without this the white background color was being overwritten

Screenshot 2023-11-07 at 4 02 26 PM

**Review by adamwoodnz — APPROVED** [review]
Made a small change, now LGTM, thanks!
