### PR TITLE
Fix redundant empty result set messages

### LINKED ISSUE #338: Redundant empty result set messages
We show 2 messages that speak to the search results:

- `0 results found for “23rasdfasdf”.`
- `Sorry, but nothing matched your search terms.`. 

We probably don't need the first one when the result set is empty.

# Screenshot
Screenshot 2023-11-06 at 3 48 58 PM

### PR DESCRIPTION
**Pull request by outdoor2kode**
Fixes #338 

This PR fixes redundant empty result set messages by returning earlier when `$results_count === 0`.
`0 results found for “xxxxxxx”.` is removed.

## Screenshot
image

### CODE REVIEW

File: source/wp-content/themes/wporg-developer-2023/src/search-results-context/index.php [hunk 1]
```diff
@@ -22,8 +22,13 @@ function render( $attributes ) {
 		return '';
 	}
 
-	$posts_per_page = get_query_var( 'posts_per_page' );
 	$results_count = $wp_query->found_posts;
+
+	if ( 0 <= $results_count ) {
```
Comment (adamwoodnz) [inline source/wp-content/themes/wporg-developer-2023/src/search-results-context/index.php]: I think this should be changed otherwise the count will not be shown for any count over 0
```suggestion
	if ( 0 === $results_count ) {
```

**Review by adamwoodnz — CHANGES_REQUESTED** [review]
Message is removed for all result counts at present, see suggestion inline 🙂

File: source/wp-content/themes/wporg-developer-2023/src/search-results-context/index.php (hunk 1 above)
Comment (outdoor2kode) [reply source/wp-content/themes/wporg-developer-2023/src/search-results-context/index.php]: ah... it was `$results_count <= 0` in the first place, and then yoda standard came in..
Thanks.

**Review by adamwoodnz — APPROVED** [review]
LGTM :shipit:
